// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/listings/views/feed_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vault_clothes/features/auth/viewmodels/auth_view_model.dart'
    as _i7;
import 'package:vault_clothes/features/favorites/viewmodels/favorites_view_model.dart'
    as _i6;
import 'package:vault_clothes/features/listings/models/listing_model.dart'
    as _i3;
import 'package:vault_clothes/features/listings/viewmodels/feed_view_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedViewModel extends _i1.Mock implements _i2.FeedViewModel {
  @override
  List<_i3.ListingModel> get listings =>
      (super.noSuchMethod(
            Invocation.getter(#listings),
            returnValue: <_i3.ListingModel>[],
            returnValueForMissingStub: <_i3.ListingModel>[],
          )
          as List<_i3.ListingModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? value) => super.noSuchMethod(
    Invocation.method(#setLoading, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? value) => super.noSuchMethod(
    Invocation.method(#setError, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> runSafe(_i4.Future<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FavoritesViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesViewModel extends _i1.Mock
    implements _i6.FavoritesViewModel {
  @override
  _i4.Stream<List<_i3.ListingModel>> get favoritesStream =>
      (super.noSuchMethod(
            Invocation.getter(#favoritesStream),
            returnValue: _i4.Stream<List<_i3.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i3.ListingModel>>.empty(),
          )
          as _i4.Stream<List<_i3.ListingModel>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isFavorite(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [listingId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> toggleFavorite(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [listingId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? value) => super.noSuchMethod(
    Invocation.method(#setLoading, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? value) => super.noSuchMethod(
    Invocation.method(#setError, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> runSafe(_i4.Future<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i7.AuthViewModel {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> register(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, displayName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setLoading(bool? value) => super.noSuchMethod(
    Invocation.method(#setLoading, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? value) => super.noSuchMethod(
    Invocation.method(#setError, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> runSafe(_i4.Future<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
