// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/listings/views/listing_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vault_clothes/features/favorites/viewmodels/favorites_view_model.dart'
    as _i2;
import 'package:vault_clothes/features/listings/models/listing_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoritesViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesViewModel extends _i1.Mock
    implements _i2.FavoritesViewModel {
  @override
  _i3.Stream<List<_i4.ListingModel>> get favoritesStream =>
      (super.noSuchMethod(
            Invocation.getter(#favoritesStream),
            returnValue: _i3.Stream<List<_i4.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.ListingModel>>.empty(),
          )
          as _i3.Stream<List<_i4.ListingModel>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isFavorite(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [listingId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> toggleFavorite(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [listingId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? value) => super.noSuchMethod(
    Invocation.method(#setLoading, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? value) => super.noSuchMethod(
    Invocation.method(#setError, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> runSafe(_i3.Future<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [action]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
