// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/listings/services/listing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vault_clothes/core/services/database_connector.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DatabaseConnector].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseConnector extends _i1.Mock implements _i2.DatabaseConnector {
  @override
  _i3.Future<Map<String, dynamic>?> getDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDocument, [collection, id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> saveDocument(
    String? collection,
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveDocument, [collection, id, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> addDocument(
    String? collection,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDocument, [collection, data]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#addDocument, [collection, data]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#addDocument, [collection, data]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateDocument(
    String? collection,
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [collection, id, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(String? collection, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [collection, id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> collectionStream(
    String? collection, {
    String? orderBy,
    bool? descending = false,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #collectionStream,
              [collection],
              {#orderBy: orderBy, #descending: descending, #limit: limit},
            ),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);
}
