// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCJHZIy647rZAOv-lf7pmkn1pPMkgLAA',
    appId: '1:126162450866:web:8914841c341307cd2e8cab',
    messagingSenderId: '126162450866',
    projectId: 'vault-clothes-app',
    authDomain: 'vault-clothes-app.firebaseapp.com',
    storageBucket: 'vault-clothes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8T2LF1yPBIVkMCzEw5K32Le8C5nXRlhg',
    appId: '1:126162450866:ios:7ca72110f527226f2e8cab',
    messagingSenderId: '126162450866',
    projectId: 'vault-clothes-app',
    storageBucket: 'vault-clothes-app.firebasestorage.app',
    iosBundleId: 'com.vaultclothes.vaultClothes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExGg1kutXZQyjHCeuxRFQ4pX23d-T1N4',
    appId: '1:126162450866:android:169e333c3b2f0d0c2e8cab',
    messagingSenderId: '126162450866',
    projectId: 'vault-clothes-app',
    storageBucket: 'vault-clothes-app.firebasestorage.app',
  );

}