// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/trust/viewmodels/profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vault_clothes/features/auth/models/user_model.dart' as _i5;
import 'package:vault_clothes/features/listings/models/filter_options.dart'
    as _i9;
import 'package:vault_clothes/features/listings/models/listing_model.dart'
    as _i8;
import 'package:vault_clothes/features/listings/services/listing_service.dart'
    as _i7;
import 'package:vault_clothes/features/trust/models/review_model.dart' as _i6;
import 'package:vault_clothes/features/trust/models/trust_info_model.dart'
    as _i2;
import 'package:vault_clothes/features/trust/services/trust_info_manager.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrustInfoModel_0 extends _i1.SmartFake
    implements _i2.TrustInfoModel {
  _FakeTrustInfoModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrustInfoManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrustInfoManager extends _i1.Mock implements _i3.TrustInfoManager {
  @override
  _i4.Future<_i5.UserModel?> getSellerProfile(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerProfile, [sellerId]),
            returnValue: _i4.Future<_i5.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.UserModel?>.value(),
          )
          as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<_i2.TrustInfoModel> getTrustInfo(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrustInfo, [sellerId]),
            returnValue: _i4.Future<_i2.TrustInfoModel>.value(
              _FakeTrustInfoModel_0(
                this,
                Invocation.method(#getTrustInfo, [sellerId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.TrustInfoModel>.value(
              _FakeTrustInfoModel_0(
                this,
                Invocation.method(#getTrustInfo, [sellerId]),
              ),
            ),
          )
          as _i4.Future<_i2.TrustInfoModel>);

  @override
  _i4.Stream<List<_i6.ReviewModel>> getReviewsStream(
    String? sellerId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsStream, [sellerId], {#limit: limit}),
            returnValue: _i4.Stream<List<_i6.ReviewModel>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i6.ReviewModel>>.empty(),
          )
          as _i4.Stream<List<_i6.ReviewModel>>);

  @override
  _i4.Future<List<_i6.ReviewModel>> getReviews(
    String? sellerId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [sellerId], {#limit: limit}),
            returnValue: _i4.Future<List<_i6.ReviewModel>>.value(
              <_i6.ReviewModel>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i6.ReviewModel>>.value(
              <_i6.ReviewModel>[],
            ),
          )
          as _i4.Future<List<_i6.ReviewModel>>);
}

/// A class which mocks [ListingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListingService extends _i1.Mock implements _i7.ListingService {
  @override
  _i4.Future<void> createListing(_i8.ListingModel? listing) =>
      (super.noSuchMethod(
            Invocation.method(#createListing, [listing]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i8.ListingModel?> getListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListing, [id]),
            returnValue: _i4.Future<_i8.ListingModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i8.ListingModel?>.value(),
          )
          as _i4.Future<_i8.ListingModel?>);

  @override
  _i4.Stream<List<_i8.ListingModel>> getFeed() =>
      (super.noSuchMethod(
            Invocation.method(#getFeed, []),
            returnValue: _i4.Stream<List<_i8.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i8.ListingModel>>.empty(),
          )
          as _i4.Stream<List<_i8.ListingModel>>);

  @override
  _i4.Stream<List<_i8.ListingModel>> getUserListings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserListings, [userId]),
            returnValue: _i4.Stream<List<_i8.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i8.ListingModel>>.empty(),
          )
          as _i4.Stream<List<_i8.ListingModel>>);

  @override
  _i4.Stream<List<_i8.ListingModel>> searchListings(
    _i9.FilterOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchListings, [options]),
            returnValue: _i4.Stream<List<_i8.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i8.ListingModel>>.empty(),
          )
          as _i4.Stream<List<_i8.ListingModel>>);

  @override
  _i4.Future<void> deleteListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListing, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
