// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/listings/viewmodels/feed_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vault_clothes/features/listings/models/listing_model.dart'
    as _i4;
import 'package:vault_clothes/features/listings/services/listing_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ListingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListingService extends _i1.Mock implements _i2.ListingService {
  @override
  _i3.Future<void> createListing(_i4.ListingModel? listing) =>
      (super.noSuchMethod(
            Invocation.method(#createListing, [listing]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ListingModel?> getListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListing, [id]),
            returnValue: _i3.Future<_i4.ListingModel?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.ListingModel?>.value(),
          )
          as _i3.Future<_i4.ListingModel?>);

  @override
  _i3.Stream<List<_i4.ListingModel>> getFeed() =>
      (super.noSuchMethod(
            Invocation.method(#getFeed, []),
            returnValue: _i3.Stream<List<_i4.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.ListingModel>>.empty(),
          )
          as _i3.Stream<List<_i4.ListingModel>>);

  @override
  _i3.Stream<List<_i4.ListingModel>> getUserListings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserListings, [userId]),
            returnValue: _i3.Stream<List<_i4.ListingModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.ListingModel>>.empty(),
          )
          as _i3.Stream<List<_i4.ListingModel>>);

  @override
  _i3.Future<void> deleteListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListing, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
