// Mocks generated by Mockito 5.4.6 from annotations
// in vault_clothes/test/features/search/views/search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vault_clothes/features/listings/models/filter_options.dart'
    as _i2;
import 'package:vault_clothes/features/listings/models/listing_model.dart'
    as _i4;
import 'package:vault_clothes/features/search/viewmodels/search_view_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFilterOptions_0 extends _i1.SmartFake implements _i2.FilterOptions {
  _FakeFilterOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchViewModel extends _i1.Mock implements _i3.SearchViewModel {
  @override
  List<_i4.ListingModel> get results =>
      (super.noSuchMethod(
            Invocation.getter(#results),
            returnValue: <_i4.ListingModel>[],
            returnValueForMissingStub: <_i4.ListingModel>[],
          )
          as List<_i4.ListingModel>);

  @override
  _i2.FilterOptions get filterOptions =>
      (super.noSuchMethod(
            Invocation.getter(#filterOptions),
            returnValue: _FakeFilterOptions_0(
              this,
              Invocation.getter(#filterOptions),
            ),
            returnValueForMissingStub: _FakeFilterOptions_0(
              this,
              Invocation.getter(#filterOptions),
            ),
          )
          as _i2.FilterOptions);

  @override
  bool get isSearching =>
      (super.noSuchMethod(
            Invocation.getter(#isSearching),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(
            Invocation.getter(#hasError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#updateSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFilters(_i2.FilterOptions? newFilters) => super.noSuchMethod(
    Invocation.method(#updateFilters, [newFilters]),
    returnValueForMissingStub: null,
  );

  @override
  void clearFilters() => super.noSuchMethod(
    Invocation.method(#clearFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? value) => super.noSuchMethod(
    Invocation.method(#setLoading, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? value) => super.noSuchMethod(
    Invocation.method(#setError, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> runSafe(_i5.Future<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [action]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
